@echo off
echo Iniciando o Servidor de Traducao...
cd ..
start npm run tradutor
echo Aguardando o servidor iniciar...
timeout /t 3 /nobreak > NUL
echo Abrindo o navegador...
start http://localhost:3001
