-- Script SQL para ser executado no SQL Editor do Supabase

-- 1. Criar a tabela de versículos bíblicos
CREATE TABLE IF NOT EXISTS verses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book TEXT NOT NULL,
    chapter INTEGER NOT NULL,
    verse INTEGER NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar índices para acelerar a busca de capítulos e versículos
CREATE INDEX IF NOT EXISTS idx_verses_book_chapter ON verses (book, chapter);
CREATE INDEX IF NOT EXISTS idx_verses_book_chap_verse ON verses (book, chapter, verse);
CREATE UNIQUE INDEX IF NOT EXISTS idx_verses_unique_ref ON verses (book, chapter, verse);

-- 3. Habilitar RLS (Row Level Security)
ALTER TABLE verses ENABLE ROW LEVEL SECURITY;

-- 4. Remover políticas antigas se existirem
DROP POLICY IF EXISTS "Leitura publica de versiculos" ON verses;
DROP POLICY IF EXISTS "Insercao para seed" ON verses;
DROP POLICY IF EXISTS "Acesso total de versiculos" ON verses;

-- 5. Criar política de acesso total (leitura e escrita para o seed)
CREATE POLICY "Acesso total de versiculos" 
ON verses FOR ALL 
USING (true) 
WITH CHECK (true);


-- =========================================================================
-- BANCO DE COMENTÁRIOS BÍBLICOS (Para RAG com IA Local)
-- =========================================================================

-- 1. Criar a tabela de comentários
CREATE TABLE IF NOT EXISTS commentaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author TEXT NOT NULL,          -- Nome do autor (ex: 'Spurgeon', 'Moody', 'Matthew Henry')
    book TEXT NOT NULL,            -- Livro (ex: 'Gênesis', 'João')
    chapter INTEGER NOT NULL,      -- Capítulo (ex: 1)
    verse INTEGER,                 -- Versículo (pode ser NULL se o comentário for sobre o capítulo inteiro)
    text TEXT NOT NULL,            -- O texto do comentário
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar índices para acelerar a busca por referências e autor
CREATE INDEX IF NOT EXISTS idx_commentaries_ref ON commentaries (book, chapter, verse);
CREATE INDEX IF NOT EXISTS idx_commentaries_author ON commentaries (author);

-- 3. Habilitar RLS (Row Level Security)
ALTER TABLE commentaries ENABLE ROW LEVEL SECURITY;

-- 4. Remover políticas antigas de comentários se existirem
DROP POLICY IF EXISTS "Leitura publica de comentarios" ON commentaries;
DROP POLICY IF EXISTS "Acesso total de comentarios" ON commentaries;

-- 5. Criar política de acesso total (leitura e escrita)
CREATE POLICY "Acesso total de comentarios" 
ON commentaries FOR ALL 
USING (true) 
WITH CHECK (true);

-- 6. Exemplo de inserção de dados de teste (rode no SQL Editor para testar)
-- INSERT INTO commentaries (author, book, chapter, verse, text) VALUES
-- ('Spurgeon', 'Gênesis', 1, 1, 'No princípio, Deus criou os céus e a terra. Aqui vemos a majestade do Criador iniciando toda a existência a partir do nada.'),
-- ('Moody', 'Gênesis', 1, NULL, 'Todo este capítulo demonstra a soberania divina em ordenar o caos. Cada dia é um passo em direção ao plano salvífico final.');

