-- Script SQL para ser executado no SQL Editor do Supabase

-- 1. Criar a tabela de versículos bíblicos
CREATE TABLE IF NOT EXISTS verses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book TEXT NOT NULL,
    chapter INTEGER NOT NULL,
    verse INTEGER NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar índices para acelerar a busca de capítulos e versículos
CREATE INDEX IF NOT EXISTS idx_verses_book_chapter ON verses (book, chapter);
CREATE INDEX IF NOT EXISTS idx_verses_book_chap_verse ON verses (book, chapter, verse);
CREATE UNIQUE INDEX IF NOT EXISTS idx_verses_unique_ref ON verses (book, chapter, verse);

-- 3. Habilitar RLS (Row Level Security)
ALTER TABLE verses ENABLE ROW LEVEL SECURITY;

-- 4. Remover políticas antigas se existirem
DROP POLICY IF EXISTS "Leitura publica de versiculos" ON verses;
DROP POLICY IF EXISTS "Insercao para seed" ON verses;
DROP POLICY IF EXISTS "Acesso total de versiculos" ON verses;

-- 5. Criar política de acesso total (leitura e escrita para o seed)
CREATE POLICY "Acesso total de versiculos" 
ON verses FOR ALL 
USING (true) 
WITH CHECK (true);
